// ------------------------    STATUS CODES    -------------------
exports.STATUS_CODES = {
  SUCCESS_CODE: 1,
  FAILURE_CODE: 2,
  // 1XX INFORMATIONAL
  CONTINUE: 100,
  SWITCHING_PROTOCOLS: 101,
  PROCESSING: 102,
  EARLY_HINTS: 103,

  // 2XX SUCCESS
  SUCCESS: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NON_AUTHORITATIVE_INFORMATION: 203,
  NO_CONTENT: 204,
  RESET_CONTENT: 205,
  PARTIAL_CONTENT: 206,
  MULTI_STATUS: 207,
  ALREADY_REPORTED: 208,
  IM_USED: 226,

  // 3XX REDIRECTION
  MULTIPLE_CHOICES: 300,
  MOVED_PERMANENTLY: 301,
  FOUND: 302,
  SEE_OTHER: 303,
  NOT_MODIFIED: 304,
  USE_PROXY: 305,
  TEMPORARY_REDIRECT: 307,
  PERMANENT_REDIRECT: 308,

  // 4XX CLIENT ERROR
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  NOT_ALLOWED: 405,
  NOT_ACCEPTABLE: 406,
  PROXY_AUTHENTICATION_REQUIRED: 407,
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  GONE: 410,
  LENGTH_REQUIRED: 411,
  PRECONDITION_FAILED: 412,
  PAYLOAD_TOO_LARGE: 413,
  URI_TOO_LONG: 414,
  UNSUPPORTED_MEDIA_TYPE: 415,
  RANGE_NOT_SATISFIABLE: 416,
  EXPECTATION_FAILED: 417, // Do not change this message frontend validation hendle on this message
  UN_PROCESSABLE_ENTITY: 422,
  VALIDATION_ERROR: 422,
  NOT_VALID_DATA: 422,
  LOCKED: 423,
  FAILED_DEPENDENCY: 424,
  UNORDERED_COLLECTION: 425,
  UPGRADE_REQUIRED: 426,
  PRECONDITION_REQUIRED: 428,
  TOO_MANY_REQUESTS: 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
  UNAVAILABLE_FOR_LEGAL_REASONS: 451,

  // 5XX SERVER ERROR
  SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  HTTP_VERSION_NOT_SUPPORTED: 505,
  VARIANT_ALSO_NEGOTIATES: 506,
  INSUFFICIENT_STORAGE: 507,
  LOOP_DETECTED: 508,
  BANDWIDTH_LIMIT_EXCEEDED: 509,
  NOT_EXTENDED: 510,
  NETWORK_AUTHENTICATION_REQUIRED: 511,
  BRIANTREE_REFUND_ISSUE: 512,
};

exports.STATUS_MESSAGE = {
  USER: {
    USER_LOGIN: "Login successfully",
    USER_INFO: "User data fetch successfully"
  },
  ACCOUNT: {
    CREATE_ACCOUNT: "Account created successfully"
  },
  SALES: {
    SALES_RECORD_CREATE: "Sales record created successfully",
    SALES_RECORD_UPDATE: "Sales record updated successfully",
    SALES_RECORD_STATUS_UPDATE: "Sales record ready for review status update successfully",
    SALES_STATUS_UPDATE_APPROVED_SALES_MANAGER: "Sales record approves by sales manager successfully",
    APPROVED_SUB_ADMIN: "Sales record approved by sub admin successfully",
    SALES_RECORDS: "Sales records fetched successfully"
  },
  VALIDATION: {
    USER: {
      INVALID_CREDENTIAL: "Invalid email or password"
    },
    TOKEN: {
      TOKEN_VALIDATION: "Invalid login token"
    }
  }
};

exports.STATUS = {
  ACTIVE: 1,
  IN_ACTIVE: 2,
  DELETE: 3
}

exports.SALES_STATUS = {
  ACTIVE: 1,
  IN_ACTIVE: 2,
  SALES_MANAGER_APPROVE: 3,
  SUB_ADMIN_APPROVE: 4
}

exports.ROLE = {
  SUPER_ADMIN: 1,
  SUB_ADMIN: 2,
  SALES_MANAGER: 3,
  EMPLOYEE: 4
}